add masking

diff --git a/main b/main
--- a/main
+++ b/main
@@ -10,9 +10,15 @@ mkdir -p output
 
 echo "Computing colored FA..."
 singularity exec -e docker://brainlife/dipy:1.4.1 python compute_cfa.py -dwi $dwi -bvals $bvals -bvecs $bvecs
+
+echo "Masking colored FA..."
+singularity exec -e docker://brainlife/fsl:6.0.1 mask.sh $dwi
+
+cp cfa_masked.nii.gz output/peaks.nii.gz
+
 if [ -f 'output/peaks.nii.gz' ]; then 
     echo "Colored FA computed."
 else 
-	echo "Colored FA missing."
-	exit 1
+    echo "Colored FA missing."
+    exit 1
 fi
