Update main

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,15 +1,14 @@
 #!/bin/bash
-#PBS -l nodes=1:ppn=16
-#PBS -l walltime=02:00:00
+#PBS -k o
+#PBS -l nodes=1:ppn=4,walltime=00:30:00,vmem=4gb
 
-# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
-# 
-# This is the main file run by the brainlife.io orchestration system
-#
-# Author: Franco Pestilli
+mkdir -p output
 
-# make output directory
-mkdir -p out_dir
-
-# run the actual python code
-singularity exec docker://brainlife/dipy:1.1.1 python3 main.py
+echo "Computing colored FA..."
+singularity exec -e docker://brainlife/dipy:1.4.1 python compute_cfa.py -dwi dwi.nii.gz -bvals dwi.bvals -bvecs dwi.bvecs
+if [ -f 'output/peaks.nii.gz' ]; then 
+    echo "Colored FA computed."
+else 
+	echo "Colored FA missing."
+	exit 1
+fi
